### ISSUE TITLE
1min and 5min datalogger files

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#108]
@roylrich Could you remind me what the deal is the the "1min" and "5min" datalogger files? We are going to process them through the pipeline, right?

E.g. `PNNL_31_sapflow_1min_20210816000006.dat`

Thanks

**Comment by roylrich** [comment]
> @roylrich Could you remind me what the deal is the the "1min" and "5min" datalogger files? We are going to process them through the pipeline, right?
> 
> E.g. `PNNL_31_sapflow_1min_20210816000006.dat`
> 
> Thanks

These were setup for events, I don't know if anyone uses them? Could we process for maybe 1 month around tempest evenst?

**Comment by bpbond** [comment]
If they're valid data, all good, let's process! No reason not to.
