### ISSUE TITLE
Remove small weird files

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#110]
@roylrich These two files should be deleted (I think) from the raw data archive; it looks like there was some initial confusion on the naming, and after this it's uniformly TerosTableC. I am excluding them from our data release.

COMPASS_GCW_W_431_TerosTableA_20221109000108.dat
COMPASS_GCW_W_431_TerosTableB_20221109000111.dat

**Comment by roylrich** [comment]
Thanks

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ben Bond-Lamberty ***@***.***>
Sent: Saturday, January 20, 2024 11:48:09 AM
To: COMPASS-DOE/data-workflows ***@***.***>
Cc: Rich, Roy ***@***.***>; Mention ***@***.***>
Subject: [COMPASS-DOE/data-workflows] Remove small weird files (Issue #110)


External Email - Exercise Caution

@roylrich<https://github.com/roylrich> These two files should be deleted (I think) from the raw data archive; it looks like there was some initial confusion on the naming, and after this it's uniformly TerosTableC. I am excluding them from our data release.

COMPASS_GCW_W_431_TerosTableA_20221109000108.dat
COMPASS_GCW_W_431_TerosTableB_20221109000111.dat
