### ISSUE TITLE
Mirror TEMPEST data into GCW

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#116]
Request from @wilsonsj100 

•	GCReW transect issue: just to make sure I understand, you’d like the “TMP” control plot and EXO data mirrored into the “GCW” data files? So GCW will now have “UP”, “TR”, and “W” plots, just like the other synoptic sites? That seems sensible and easy to do, although we’ll want to make sure the metadata clearly explain this.

**Comment by bpbond** [comment]
@wilsonsj100 Can you confirm this is what you want:

TEMPEST data including all plots:

<img width="660" alt="Screenshot 2024-04-02 at 10 29 21 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/24e70ed3-06a5-4bdb-a9a4-4a45bd09a57c">

Just the control plot data are now mirrored into the GCW folder:

<img width="703" alt="Screenshot 2024-04-02 at 10 30 02 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/c799a65d-8a55-431c-94c4-362146cd58b1">

Internally, they're marked as GCW upland:

<img width="750" alt="Screenshot 2024-04-02 at 10 31 33 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/de98722c-0a92-462f-a94d-32a2df4d1980">

...and so appear in the final L1 data as GCW UP files that are duplicates of the TMP C data:

<img width="778" alt="Screenshot 2024-04-02 at 10 33 11 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/f9a70ec7-b76b-4755-b540-0823932a0ac7">
<img width="773" alt="Screenshot 2024-04-02 at 10 34 06 AM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/a35424db-39ab-4592-9331-5063d6b45e93">

**Comment by wilsonsj100** [comment]
Yes, this is what I want. This makes it easier for comparing across the sites rather than having to pull data from the tempest control releases. Thank you so much! 

One thing I was thinking about is whether or not we need all the TEMPEST data or if we want to just pull what would match a synoptic site. For example, TEMPEST has a lot more teros sensors than the synoptic sites, but I think it is probably okay for users to decide what data they want to include? 

Open to thoughts here.

**Comment by bpbond** [comment]
Yeah, I think the choice of specific data is on users; I don't want to burden the processing pipeline with that level of additional complexity/specificity. I'd suggest we add a note to the GCW metadata file about this, though.

I'll open a PR for this and tag @stephpenn1 for her feedback.

**Comment by stephpenn1** [comment]
Great idea to do this @wilsonsj100 and @bpbond. Agreed with Ben, it's certainly possible but would take a lot of decisions and edits to the pipeline. We would always make a statement that if we want to cross compare synoptic sites, people can use only the depth profiles. 

Will look out for the PR Ben
