### ISSUE TITLE
Rework SWH plot naming and structure

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#117]
Again that @wilsonsj100 making trouble

>The second issue is a bit more straightforward; the Sweet Hall site transect is a bit complicated because it includes a forested swamp. The transect goes wetland, transition, forested swamp, then upland. Unfortunately, we only really realized this fully after starting to sample and putting in the infrastructure. This means that right now all of the sensor data that is labeled Upland needs to be changed to Swamp. We are planning to install teros sensors and an aquatroll in the true upland in the next few weeks and that will then be called our upland moving forward.

**Comment by bpbond** [comment]
@roylrich says:

>   Thanks SW for getting this moving.  The TerosTableB and WaterLevel600B tables will be the new UPLAND site. I still have a code change to get the TerosTableB table reporting correctly. 

![image](https://github.com/COMPASS-DOE/data-workflows/assets/1956468/8b87b32d-6ead-422b-bbe4-e5de2d206397)

**Comment by bpbond** [comment]
@roylrich @wilsonsj100 What is the official "turn on" date for the new upland data streams? I need to know this for renaming upland data to swamp.

Right now it looks like W (wetland), TR (= the swamp?), and UP (upland) files are being written.

**Comment by roylrich** [comment]
@bpbond: these sites are a bit weird because they are a sub-module on the UP site. I need to check how these are labelled and also check the soil moisture data.

**Comment by bpbond** [comment]
OK, I see the new Sweet Hall data and want to double-check correct action before proceeding.

| SWH datalogger table | Data start | Code should |
| ------------------------------------- | --------- | ---------------------------------- |
| Compass_SWH_UP_423_CheckTable | May 2023 | Change to "SWAMP" in processing |
| Compass_SWH_UP_423_SapflowA | May 2023 | Change to "SWAMP" |
| Compass_SWH_UP_423_TerosTableA | May 2023 | Change to "SWAMP" |
| Compass_SWH_UP_423_TerosTableB | March 2024 | Leave as "UP" |
| Compass_SWH_UP_423_WaterLevel600A | May 2023 | Change to "SWAMP" |
| Compass_SWH_UP_423_WaterLevel600B | March 2024 | Leave as "UP" |

@roylrich @wilsonsj100 :

1. **Is the action table above correct?**
2. **Will everything continue to be labeled as UP on datalogger going forward?** I mean, there won't be a datalogger code change so that output tables are saying SWAMP; instead we will always depend on R for this step?

Thanks!

**Comment by bpbond** [comment]
One more:

3. Are the new TEROS sensors (n=4) at the new upland plot all 10 cm? Or other depths?

**Comment by wilsonsj100** [comment]
Hey Ben, 
Right now there are only two TEROS sensors installed at SWH. We are planning to put in the other ones this month. I need to check the numbers that we used.

**Comment by bpbond** [comment]
Thank you! Hmm. How do you want to handle this? Include numbers 1 and 5 in the v1-0 release for those depths, and then reassign later as needed?

**Comment by wilsonsj100** [comment]
I think that makes sense. We will not be out there to install the others until the 24th of April (after the ESS PI meeting and the release), so we can put this out with 1 and 5 for now. If it is not a coding issue for Roy, then we may also be able to keep these addresses the same.

**Comment by bpbond** [comment]
👍  OK!

**Comment by bpbond** [comment]
I have assigned TEROS 1-4 as 10 cm, and 5-6 and 30 cm, following the pattern in many other plots; if you guys change this please let me and @stephpenn1 know.

Happy Friday!
