### ISSUE TITLE
Add plot locations for teros and other applicable TEMPEST sensors in L1 data

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/data-workflows#118]
Add grid cells to teros and other applicable sensors in TEMPEST for spatial identification

**Comment by bpbond** [comment]
Do we want to add this to the L1 data Itself? It'll be a column that (1) is only used for TEMPEST and (2) is very redundant (because TEROS sensors are always in the same place).

What about including the location data in the L1 metadata, or telling users where they can find it?

**Comment by stephpenn1** [comment]
I think we should include it as a file in the L1 and L2 metadata, and make sure it can be joined easily with any new columns we add via #124
