### ISSUE TITLE
Battery versus solar voltages

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#123]
@roylrich @stephpenn1 @selinalcheng 

Right now we have 11-13 volts as the bounds for voltage. This is true for the battery voltage, but not solar:

![Screenshot 2024-04-01 at 12 28 57 PM](https://github.com/COMPASS-DOE/data-workflows/assets/1956468/5ebaf99c-b3e9-40a1-b40c-507de01b492a)

Is there a standard range to expect for the cataloger's `SolarV` loggernet variable? From spot checking, it looks like varies between 24V and 29V.

**Comment by roylrich** [comment]
Solar voltage should be 0 to 30v. You are correct in that UT is typically around 24v for all sites but owc. Owc is in grid. And has 12v incoming t I think.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bpbond** [comment]
Thanks Roy! I'll make that change.
