### ISSUE TITLE
v0.9 L1 TEMPEST data only has sapflow and teros 

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/data-workflows#144]
Looks like we are only writing out TMP data for teros and sapflow. The design_table does have research names for aquatroll, but they are not included in the final.

Taking a look at a data file:
<img width="662" alt="image" src="https://github.com/COMPASS-DOE/data-workflows/assets/20341158/97266021-dd4e-4daa-aac8-6e6dd996ce85">

Produces:
<img width="150" alt="image" src="https://github.com/COMPASS-DOE/data-workflows/assets/20341158/4daa8aa6-614a-4e93-950e-13fdedf9a4b2">

And pdf summary:
<img width="815" alt="image" src="https://github.com/COMPASS-DOE/data-workflows/assets/20341158/02e42e44-9ece-4423-8d24-670e809c5cf4">

**Comment by bpbond** [comment]
This is currently still true for v1-0 😞 
```r
 january_2024_data %>% filter(!is.na(value)) %>%  group_by(Plot, Instrument) %>% summarise(n = n()) %>% pivot_wider(values_from = "n", names_from = "Plot")
`summarise()` has grouped output by 'Plot'. You can override using the `.groups` argument.
# A tibble: 2 × 4
  Instrument      C      F      S
  <chr>       <int>  <int>  <int>
1 Sapflow     71262  77370  77358
2 TEROS12    400065 409617 408903
```

**Comment by bpbond** [comment]
Ah thank you @stephpenn1 -- I see the problem 🎉  -- missing entry in our bounds/units table.
