### ISSUE TITLE
Things to fix in beta

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#151]
- [x] Evan whatshisname (Toledo) should be on site contacts?
- [x] OWC past data (1980 etc)

**Comment by bpbond** [comment]
>Evan whatshisname (Toledo)

@stephpenn1 do you know this person, and whether we should add him?

**Comment by stephpenn1** [comment]
Yes, Evan Grammenidis evangelos.grammenidis@utoledo.edu

The site contact sheet should be up to date and he us marked as "Evan G."

**Comment by bpbond** [comment]
We're good here I think
