### ISSUE TITLE
Design Link Removal 

### ISSUE THREAD

**Issue by wilsonsj100** [COMPASS-DOE/data-workflows#154]
Hi Data Team, 

Does the beta version take out the design link that tells you which zone the synoptic site data are from? I guess we may be able to link it to the unique ID, but I was really liking having the design_link that told me if a sensor was in TR or WC and what depth for a teros (for example). Maybe I am just missing where this info is now. 

Thanks! 
-Steph

**Comment by bpbond** [comment]
Hi @wilsonsj100 

The information should all still be there, just split into different columns: Plot, Sensor_ID, research_name, etc.

**Comment by wilsonsj100** [comment]
![MSM_v1_data](https://github.com/COMPASS-DOE/data-workflows/assets/122289915/b1833013-a796-47d4-9234-bc910cc0c216)
Hi @bpbond

hmmm okay... maybe I am missing where that is. Here is an MSM file in the v1-0 folder for june 2023 after I download it. I am not seeing those other columns?

**Comment by bpbond** [comment]
Plot is on the far left, column A; sensor depth will be part of the research_name in H.

**Comment by wilsonsj100** [comment]
Whoops.... My bad when I subset the data I took the original column names from v0-9 and cut that column out! Thank you!
