### ISSUE TITLE
Need for standardized sensor data not on loggers

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/data-workflows#157]
This is relevant to our community fund idea, but we should make sure non-logger sensor data can be processed to a similar format + level as our campbell sensor data

**Comment by stephpenn1** [comment]
This question came up from YSI data from @amyerspigg

**Comment by bpbond** [comment]
Thanks. Just to clarify, does this mean we want non-logger data as part of L1, not just L2?

**Comment by bpbond** [comment]
Dupe of #213
