### ISSUE TITLE
Flipped solar units in design table?

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#160]
Following up on #158 , from our variable metadata file:

<img width="937" alt="Screenshot 2024-05-01 at 2 37 26 PM" src="https://github.com/COMPASS-DOE/data-workflows/assets/1956468/30f960a9-8c6e-4072-9bf3-de29d547f3d1">

But...
W/m2 = J/s/m2 is a _rate_
MJ/m2 = _amount_ of energy

So it seems like the "total solar flux" should be in MJ/m2, and the "average" should be W/m2...are the units flipped for these entries?

💡  Ah the variable names have the correct units! OK, so I think our entries are wrong.

@stephpenn1 @roylrich @selinalcheng Is this right? I mean, is it right that the metadata table is wrong? Thanks

**Comment by selinalcheng** [comment]
Yes, I think variable names/units are correct -- you can look at variable names to confirm.

**Comment by bpbond** [comment]
Sorry, does that mean you agree that the COMPASS-FME units are flipped by accident?

**Comment by selinalcheng** [comment]
Yes, I think the metadata units are flipped by accident and the units hard-coded into the loggernet variable are correct.
