### ISSUE TITLE
Tempest Redox system is beta testing

### ISSUE THREAD

**Issue by roylrich** [COMPASS-DOE/data-workflows#162]
@bpbond @stephpenn1 
I have made redox program for TEMPEST and installed on 81,82,83 loggers. We will be error check for next few days so data should not be used.

1. Protocol install table can be found [here](https://docs.google.com/document/d/1oL66WqKNcj1rnagJG56Rza-B1CYLKvJs/edit?usp=drive_link&ouid=110686121195965780388&rtpof=true&sd=true)
2. Googledoc for design table is [here](https://docs.google.com/spreadsheets/d/1v8ufNiYdj-0TKaCFkOWgBkzcZMVxjEZp/edit?usp=sharing&ouid=110686121195965780388&rtpof=true&sd=true)
Program will be sent when completed.

**Comment by bpbond** [comment]
Thanks @roylrich ! This won't make it into the v1-0 release (unless @stephpenn1 disagrees) but I've added it to the milestone for v1-1.
