### ISSUE TITLE
Rearchitecting Portage sensor workflow

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#17]
- [x] `L1a.qmd` now combines across entire site and joins with plot table
- [x] Implement units conversion based on real table
- [x] Move `do_units_conversion` to `compasstools`
- [x] Implement OOB flags based on real table - based on `research_name` and `units`
- [x] Implement a derived variable. Defined through code? CSV file?
- [x] Get feedback from SP at this point
- [x] Redo L1b
- [ ] Feedback from SP, SC, RR

**Comment by stephpenn1** [comment]
Loop me in when useful re: `Implement a derived variable`

**Comment by bpbond** [comment]
@stephpenn1 

>Implement a derived variable

I know one case, which is we that want to compute water table level based on one of the Troll600 variables (plot specific) + a site level met variable. Is that right? 

Oh sap flux is another. I think it needs sap velocity (plot) + at least PAR (site) + tree level information (separate dataset).

Do you have other specific examples please? I'm trying to think through how this will work code-wise. 

Thank you

**Comment by stephpenn1** [comment]
I need to think about this a bit more, but these should be the only variables:

| Variable         | External Data Needed |
|    :----:           |               :----:               |
| Sapflow         | ClimaVue (PAR), sapwood area         |
| Water Level (200 - nonvented)  | ClimaVue (atm pressure); inventory sheet  |
| Water Level (600 - vented)  |  inventory sheet  |

**Comment by bpbond** [comment]
Start with a `derived_table.csv`

new_research_name | research_names_needed
-- | --
sapflow_avg | sapflow,sapflow_deep

Data enters derived calculation and is filtered for `research_names_needed` entries:

Site | Plot | Tree | TIMESTAMP | research_name | value
-- | -- | -- | -- | -- | --
Portage | Upland | 001 | 2022-11-09T00:00:00Z | sapflow | 0.598
Portage | Upland | 001 | 2022-11-09T00:15:00Z | sapflow | 0.599
Portage | Upland | 001 | 2022-11-09T00:30:00Z | sapflow | 0.599
Portage | Upland | 001 | 2022-11-09T00:00:00Z | sapflow_deep | 0.581
Portage | Upland | 001 | 2022-11-09T00:15:00Z | sapflow_deep | 0.583
Portage | Upland | 001 | 2022-11-09T00:30:00Z | sapflow_deep | 0.583

This gets reshaped before passing to handler function:

Site | Plot | Tree | TIMESTAMP | sapflow | sapflow_deep
-- | -- | -- | -- | -- | --
Portage | Upland | 001 | 2022-11-09T00:00:00Z | 0.598 | 0.581
Portage | Upland | 001 | 2022-11-09T00:15:00Z | 0.599 | 0.583
Portage | Upland | 001 | 2022-11-09T00:30:00Z | 0.599 | 0.583

If handler (`DERIVED_sapflow_avg()`) is called guaranteed that data columns are available. It computes `value` and assigns `units`:

Site | Plot | Tree | TIMESTAMP | sapflow | sapflow_deep | value | units
-- | -- | -- | -- | -- | -- | -- | --
Portage | Upland | 001 | 2022-11-09T00:00:00Z | 0.598 | 0.581 | n.nn | uuu
Portage | Upland | 001 | 2022-11-09T00:15:00Z | 0.599 | 0.583 | n.nn | uuu
Portage | Upland | 001 | 2022-11-09T00:30:00Z | 0.599 | 0.583 | n.nn | uuu

Back in the caller, we assign  a new `research_name` (given in the csv) and get of unneeded computational columns (the variables that went into the derived variable). 

Site | Plot | Tree | TIMESTAMP | value | units | research_name
-- | -- | -- | -- | -- | -- | --
Portage | Upland | 001 | 2022-11-09T00:00:00Z | n.nn | uuu | sapflow_avg
Portage | Upland | 001 | 2022-11-09T00:15:00Z | n.nn | uuu | sapflow_avg
Portage | Upland | 001 | 2022-11-09T00:30:00Z | n.nn | uuu | sapflow_avg

What about new `design_link`? Where does it come from?

**Comment by bpbond** [comment]
Derived variables implemented in d7c521223d8c69b7d76bf2b31fb8bd364096a178. Output looks like this:

<img width="934" alt="Screenshot 2023-02-08 at 9 47 32 PM" src="https://user-images.githubusercontent.com/1956468/217705254-1bb63125-675b-40ce-a40c-74a1b2964742.png">

**Comment by bpbond** [comment]
@stephpenn1 I tagged you requesting feedback in the [google doc](https://docs.google.com/document/d/1DsreUaGZDGIsurH_FVRHwgS0r53h7GTL0zdEOERbPqE/edit) but otherwise I think everything here is done for meeting with SERC folks next week, closing.
