### ISSUE TITLE
csv's missing from v0-9 TMP 2023?

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/data-workflows#176]
Hi data-workflows team,
Just had a look in the v0-9 Tempest data and a few years are missing the csv's. Did these get pulled for recompiling?
Thanks for all you do!
Best,
K

**Comment by bpbond** [comment]
Hi @kendalynnm -- is there a reason you're not using the v1-0 data? That is vastly improved, longer and more complete, and definitely the recommended choice.

**Comment by kendalynnm** [comment]
Oh good to know! Will do!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
