### ISSUE TITLE
Synoptic dashboard erroring out

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/data-workflows#178]
![image](https://github.com/COMPASS-DOE/data-workflows/assets/20341158/59d66980-0e3b-477b-a2d1-f4bf73c07b0d)

**Comment by bpbond** [comment]
Thanks @stephpenn1 . Note the new TEMPEST dashboard is at https://github.com/COMPASS-DOE/TEMPESTdash -- were you running that one, or the old one here?

**Comment by stephpenn1** [comment]
This is for the synoptic site dashboard - different than TEMPESTdash

**Comment by stephpenn1** [comment]
Synoptic dash is in this repo located here: https://github.com/COMPASS-DOE/data-workflows/tree/main/synoptic_dashboard

**Comment by bpbond** [comment]
Ah, sorry!

**Comment by stephpenn1** [comment]
https://compassdashboards.shinyapps.io/synoptic_dashboard/

Also note this is low priority, I'm not sure if people still find this dashboard useful

**Comment by stephpenn1** [comment]
I've refreshed the drop token and this is back up and running
