### ISSUE TITLE
Avg vapor pressure values all 0

### ISSUE THREAD

**Issue by radha-vs** [COMPASS-DOE/data-workflows#183]
Hi all,  

In the GCW-W L1 metadata for 2024, all measurements for wx_vappress15 (average vapor pressure over 15 minute period) are 0. Does anyone know why this is or where else we could find that data? Thanks so much!

**Comment by bpbond** [comment]
Sorry @radha-vs -- I'm still catching up with things.

There was a problem with the datalogger programs, so VPD will be available going forward, but not for the extant data. See https://github.com/COMPASS-DOE/data-workflows/issues/175
