### ISSUE TITLE
Freshwater Plot in TMP data frames is Labeled as "FALSE"

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/data-workflows#186]
<img width="890" alt="Screenshot 2024-07-12 at 3 12 36 PM" src="https://github.com/user-attachments/assets/ac0993cb-86aa-48a8-bc0a-6b85930831bc">

**Comment by amyerspigg** [comment]
This appears to be the case in both of the two years I pulled 2022 and 2023.

**Comment by bpbond** [comment]
Thanks for your sharp eyes here! I started to type "omg, something is wrong, I will investigate and fix the code" ...but then realized that we're writing the freshwater plot abbreviation ("F") into that column...and R is thinking that it's a logical (TRUE/FALSE) because of that "F" I bet.

🤦 

How are you reading in this data @amyerspigg ?

**Comment by amyerspigg** [comment]
@bpbond & @stephpenn1 I am using the read_csv function

**Comment by stephpenn1** [comment]
@bpbond I'm looking into this using her download / read code and will report back

**Comment by stephpenn1** [comment]
AMP is using drive_download to access these files, so I tested used (1) her code & that function and (2) direct download from google drive; then I tried using `read_csv()` and `read.csv()` on those files and all get the same result. For files that are all Freshwater plot they are read in as "logical", see below example for the two read functions:
<img width="965" alt="image" src="https://github.com/user-attachments/assets/3c29bbdd-1d48-4c4a-b9d9-073ffe584f3f">

**Comment by stephpenn1** [comment]
For our records, this is linked to https://github.com/COMPASS-DOE/TEMPEST-1-porewater/issues/7

**Comment by bpbond** [comment]
Thank you @stephpenn1 

So right, the parser is seeing a column full of "F" characters and is assuming that's logical. @amyerspigg in your workflow, would a solution like this work?
```r
read_csv("TMP_F_20220101-20220131_L1_v1-0. csv", col_types = "ccTcdccdccdd")
```

**Comment by bpbond** [comment]
I've tweaked the code of, and added an explanatory comment about this to, our [file-reading example](https://github.com/COMPASS-DOE/data-workflows/blob/main/synoptic/data/L1/code_examples/create-time-series.R) that's included with each release.

I think it's OK to close this issue, and that the code above will be a good solution for you @amyerspigg . But please re-open if needed! Thanks
