### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#20]
To do list from meeting today with @roylrich @selinalcheng @stephpenn1 

- [x] preserve T05A information from raw - this has to be done in compasstools
- [x] output file names should include rows/cols of data
- [x] output files name could include a brief hash
- [ ] what are error codes for instruments? They should become NA
- [x] "sn" - look for this - should travel with data
- [x] TIMESTAMP_raw
- [x] L1a has the raw timestamps as well, and not 15-min averages
- [x] L1b has rounded timestamps, and only 15 min averages
- [x] metadata - generate a file-level file #31

**Comment by selinalcheng** [comment]
Roy says: you only need "sn" to travel with the data for the ExoTables, where I belei

**Comment by bpbond** [comment]
Thanks! Here's an ExoTable header:

```
"TOA5","Compass_PTR_W_311","CR1000X","28723","CR1000X.Std.05.01","CPU:COMPASS_v3.3.CR1X","53163","ExoTable"
"TIMESTAMP","RECORD","PB","Statname","Date","Time","Conductivity","FDOM_QSU","FDOM_RFU","NLF_conductivity","ODO_sat","ODO_local","ODO_MgL","Pressure_psia","Salinity_PPT","Specific_Conductivity_uScm","Wiper_Position_mv","pH","pH_mv","Temp_C","Depth_m","Battery_v","Cable_v","Wiper_Current_ma","sn","snn"
"TS","RN","","","mmddyy","hhmmss","uS/cm","QSU","RFU","uS/cm","%Sat","%SatLocal","mg/L","psia","ppt","uS/cm","mv","pH","mv","Celsius","meters","volts","volts","ma","",""
"","","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp","Smp"
```

So, is "28723" the serial number here? 🙏

**Comment by bpbond** [comment]
Bzzzzt OH I SEE you mean the "sn" and "snn" columns. Never mind, got it!

**Comment by selinalcheng** [comment]
Oh yep, sorry! Those are the column headers.

**Comment by bpbond** [comment]
All done here except for the error code issue which is also mentioned in #49
