### ISSUE TITLE
DiffVolt_Avg versus DiffVolt

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#72]
Hi @roylrich -

The TEMPEST datalogger outputs have a `sapflow` table, which in turn has fields named `DiffVolt_Avg` and `DiffVolt`. I'm assuming that I should follow the synoptic site pattern, so use the former but ignore the latter?

Thanks!

**Comment by roylrich** [comment]
I think this is ok. @stephpenn1 . Do you agree?

**Comment by stephpenn1** [comment]
Yes we use `DiffVolt_Avg` for synoptic and TEMPEST data processing so we should use that as our raw value, if I'm understanding the question correctly. I believe the average value comes from Roys logger code, and is the 15 minute average, and `DiffVolt` is maybe the last value recorded.
