### ISSUE TITLE
Mystery loggers

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#80]
Pulling https://github.com/COMPASS-DOE/data-workflows/issues/71#issuecomment-1850190302 into its own issue so it doesn't get lost.

@roylrich 

>Loggers 11, 12, 13 are the same as pakbus (pb) 41, 42, and 43 and are in control
>Loggers 21, 22, 23, are the same as pakbus (pb) 44, 45, and 46 and are fresh
>Loggers 31, 32, 33 are the same as pakbus(pb) 47,4 8, and 49 and are salt.

What about `PNNL_41`? I understand from @aestearns01 that it's actually the synoptic transition logger at GCReW, so also appears in the synoptic folder as `GCW`. Can the TEMPEST folder `PNNL_41` be ignored?

Also, what about these two loggers:
```
CR1000_2	Table1	Format
CR1000_2	Table1	RECORD
CR1000_2	Table1	Statname
CR1000_2	Table1	BattV
CR1000_2	Table1	RedoxRa({1:20})
CR1000_2	Table1	RedoxRb({1:20})
		
RedoxMU3_83	Table1	Format
RedoxMU3_83	Table1	RECORD
RedoxMU3_83	Table1	Statname
RedoxMU3_83	Table1	BattV
RedoxMU3_83	Table1	RedoxRa({1:20})
RedoxMU3_83	Table1	RedoxRb({1:20})
```

**Comment by roylrich** [comment]
This is a tricky one, as some of the data overlaps (sapflow). We should ask Nick as this was the orignal shore site. I doubt that anyone will use it for broad-scale modelling or anything that was not preliminary. The well data was first an AQ200 and then an AQ600.   So honestly, I have no idea and it should be ignored for Jan 22 objectives ?

**Comment by roylrich** [comment]
The redox logger data should be processed. I can help with this
