### ISSUE TITLE
TEMPEST sap flow reassignment - there was one in control? Add

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#86]

**Comment by aestearns01** [comment]
Control Plot
SF C8 (Tree ID 1436) died
Logger 11, Port 2
deactivated around 10am 6/3/22
Replaced with SF C19 (Tree ID 1451)
Logger 11, Port 2
Connected around 10am 6/3/22

**Comment by bpbond** [comment]
🎉 thank you @aestearns01 !
