### ISSUE TITLE
What's the initial version number?

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/data-workflows#97]
Are we announcing v1.0 of the sensor data next week? Or declaring the data still in beta for a couple months, so v0.9 or something?

**Comment by stephpenn1** [comment]
I think since we anticipate not having everything filled out to 100%, we should start with 0.9. I will add to my to-do list to create a similar readme to the EXCHANGE one that includes a versioning table for people to reference in the google drive

**Comment by bpbond** [comment]
I agree. Thank you @stephpenn1 

Re versioning table — right now I have a "changelog" in the README [here](https://github.com/COMPASS-DOE/data-workflows/blob/main/synoptic/data_TEST/L1_metadata/README_v%3F%3F%3F.txt), to be distributed with every data release. Does that work?

**Comment by stephpenn1** [comment]
Ah yeah, does this get automatically produced?

**Comment by bpbond** [comment]
Yes, automatically included with each release. We need to write the changelog entry itself, of course.

**Comment by stephpenn1** [comment]
Okay yes we'll just stick with this then. Thanks!

**Comment by bpbond** [comment]
Thanks so much!
